USE [master]
GO
/****** Object:  Database [Homework01]    Script Date: 18-May-24 00:07:03 ******/
CREATE DATABASE [Homework01]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Homework01', FILENAME = N'D:\Docs\DATA\Homework01.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Homework01_log', FILENAME = N'D:\Docs\DATA\Homework01_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [Homework01] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Homework01].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Homework01] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Homework01] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Homework01] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Homework01] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Homework01] SET ARITHABORT OFF 
GO
ALTER DATABASE [Homework01] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Homework01] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Homework01] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Homework01] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Homework01] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Homework01] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Homework01] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Homework01] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Homework01] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Homework01] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Homework01] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Homework01] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Homework01] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Homework01] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Homework01] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Homework01] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Homework01] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Homework01] SET RECOVERY FULL 
GO
ALTER DATABASE [Homework01] SET  MULTI_USER 
GO
ALTER DATABASE [Homework01] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Homework01] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Homework01] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Homework01] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Homework01] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Homework01] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'Homework01', N'ON'
GO
ALTER DATABASE [Homework01] SET QUERY_STORE = ON
GO
ALTER DATABASE [Homework01] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [Homework01]
GO
/****** Object:  Table [dbo].[AchievmentType]    Script Date: 18-May-24 00:07:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AchievmentType](
	[AchievmentTypeId] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
	[Description] [nvarchar](50) NOT NULL,
	[ParticipationRate] [int] NOT NULL,
 CONSTRAINT [PK_AchievmentType] PRIMARY KEY CLUSTERED 
(
	[AchievmentTypeId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Course]    Script Date: 18-May-24 00:07:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Course](
	[CourseId] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
	[Credit] [int] NOT NULL,
	[AcademicYear] [date] NOT NULL,
	[Semester] [int] NOT NULL,
 CONSTRAINT [PK_Course] PRIMARY KEY CLUSTERED 
(
	[CourseId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Grade]    Script Date: 18-May-24 00:07:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Grade](
	[GradeId] [int] IDENTITY(1,1) NOT NULL,
	[StudentID] [int] NOT NULL,
	[CourseID] [int] NOT NULL,
	[TeacherID] [int] NOT NULL,
	[Grade] [nvarchar](50) NOT NULL,
	[Comment] [datetime] NULL,
	[CreatedDate] [datetime] NOT NULL,
 CONSTRAINT [PK_Grade] PRIMARY KEY CLUSTERED 
(
	[GradeId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[GradeDetails]    Script Date: 18-May-24 00:07:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[GradeDetails](
	[GradeDetailsId] [int] IDENTITY(1,1) NOT NULL,
	[GradeID] [int] NOT NULL,
	[AchievmentTypeID] [int] NOT NULL,
	[AchievmentPoints] [int] NOT NULL,
	[AchievmentMaxPoints] [int] NOT NULL,
	[AchievmentDate] [datetime] NOT NULL,
 CONSTRAINT [PK_GradeDetails] PRIMARY KEY CLUSTERED 
(
	[GradeDetailsId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Student]    Script Date: 18-May-24 00:07:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Student](
	[StudentId] [int] IDENTITY(1,1) NOT NULL,
	[FirsName] [nvarchar](50) NOT NULL,
	[LastName] [nvarchar](50) NOT NULL,
	[DateOfBirth] [datetime] NOT NULL,
	[EnrolledDate] [datetime] NOT NULL,
	[Gender] [bit] NOT NULL,
	[NationalIDNumber] [nvarchar](50) NOT NULL,
	[StudentCargNumber] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Student] PRIMARY KEY CLUSTERED 
(
	[StudentId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Teacher]    Script Date: 18-May-24 00:07:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Teacher](
	[TeacherId] [int] IDENTITY(1,1) NOT NULL,
	[FirsName] [nvarchar](50) NOT NULL,
	[LastName] [nvarchar](50) NOT NULL,
	[DateOfBirth] [datetime] NOT NULL,
	[AcademicRank] [nvarchar](50) NOT NULL,
	[HireDate] [datetime] NOT NULL,
 CONSTRAINT [PK_Teacher] PRIMARY KEY CLUSTERED 
(
	[TeacherId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [Homework01] SET  READ_WRITE 
GO
